# Generated by Django 5.1 on 2024-08-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('car_model', models.CharField(max_length=100)),
                ('vin', models.CharField(max_length=17)),
                ('reservation_start_time', models.DateTimeField()),
                ('reservation_end_time', models.DateTimeField()),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
