# Generated by Django 5.1 on 2024-08-15 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingSystem', '0002_carregistration_alter_parkingspot_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carregistration',
            name='parking_spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ParkingSystem.parkingspot'),
        ),
    ]
