# Generated by Django 5.1 on 2024-08-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingSystem', '0003_carregistration_parking_spot'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
