# Generated by Django 5.1 on 2024-08-16 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingSystem', '0005_remove_carregistration_reservation_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carregistration',
            name='approved',
        ),
    ]
