# Generated by Django 5.1 on 2024-08-18 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParkingSystem', '0006_remove_carregistration_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carregistration',
            old_name='vin',
            new_name='car_plate',
        ),
        migrations.RemoveField(
            model_name='carregistration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='carregistration',
            name='name',
        ),
        migrations.RemoveField(
            model_name='carregistration',
            name='phone_number',
        ),
    ]
